### ISSUE TITLE
ankidroid fail to import

### ISSUE THREAD

**Issue by ghtesting2020** [donkuri/Kaishi#28] opened 2024-05-01 01:03 UTC
Hi i havent tried the prior versions since i only learned about Kaishi but the latest version 1.5k 2.0 fails to import with no specific error. I tried renaming it to just k.apkg but no difference.

Files imported: 0
Total cards imported: 0

Some errors occurred while importing the following files: Kaishi.1.5k.apkg
Updated 0 of 1 existing notes

Thank you

**Comment by abaga129** [comment] 2024-05-01 12:43
I'm also running into this.  I updated my note type to the new deck, but still it doesnt update anything when importing.  I also havent figured out how to get to this screen as shown in the release notes

![](https://raw.githubusercontent.com/donkuri/Kaishi/main/pics/import.webp)

**Comment by donkuri** [comment] 2024-05-06 17:25
This is weird, do you get the same issue on the desktop version?

**Comment by donkuri** [comment] 2024-05-11 20:18
Since I can't reproduce this at all, I am closing the issue. Make sure you're using the latest version of ankidroid. If it keeps happening, simply import it on desktop and then sync.

**Closed** 2024-05-11 20:18 UTC
