### ISSUE TITLE
Furigana reading needs a quick update for one of the 方 cards.

### ISSUE THREAD

**Issue by christopherball** [donkuri/Kaishi#22] opened 2024-03-15 17:33 UTC
Example sentence / audio are both using the ほう（方）reading as opposed to かた for the following card:

![image](https://github.com/donkuri/Kaishi/assets/5790394/1d76b6f0-004f-49cd-9e66-3451acc937bf)

Recommend updating the furigana for the isolated word at the top to match.

**Comment by donkuri** [comment] 2024-03-20 14:10
Fixed in the latest version, thank you.

**Comment by christopherball** [comment] 2024-03-20 15:07
Just downloaded/imported the latest release and checked this card.  While the "Word Reading" field had a value of ほう, the "Word Furigana" field still had a value of 方[かた].  I've manually fixed it in mine for the time being (方[ほう]).

**Comment by donkuri** [comment] 2024-03-20 16:18
Are you sure you downloaded the latest release? On my version, the Word Furigana field is formatted correctly.

**Comment by christopherball** [comment] 2024-03-20 16:26
Downloaded v1.3.2 and imported it over v1.3.1, which included about 15 changes as I recall in the summary window.  Didn't spot a card including 方 so I went ahead and manually checked it.

**Comment by donkuri** [comment] 2024-03-22 22:31
I can't reproduce this on any of the newer versions so I will close it for now.

**Closed** 2024-03-22 22:30 UTC
